---
- hosts: first
  gather_facts: false
  become: true
  tasks:


  - name: reboot vm
    shell: "sleep 2 && reboot"
    async: 1
    poll: 0


  - name: wait for the reboot to complete
    wait_for_connection:
      connect_timeout: 20
      sleep: 5
      delay: 60
      timeout: 300
    delegate_to: localhost
