---
- hosts: first
  gather_facts: true
  become: true
  tasks:


  - name: reboot vm
    shell: "sleep 2 && reboot"
    async: 1
    poll: 0

  - name: Validating if the WebServer port is closed.
    tags: amvalidate1
    wait_for:
        host: "{{inventory_hostname}}"
        port: "{{webserver_port}}"
        delay: 10
        timeout: 30
        state: stopped
        msg: "WebServer PORT is not yet stopped"
    when: ansible_hostname == "{{inventory_hostname}}"
    register: amvalidate1
    ignore_errors: true
