---
- name: Ansible debug module in action
  hosts: "{{ serv }}"
  remote_user: "{{ user }}"
  become: true
  become_method: sudo
  become_user: root 
  gather_facts: false
  ignore_unreachable: true
  tasks:
          - name: Print system uptime
            shell: uptime -p
            register: system_uptime
          - name: Print uptime of managed node
            debug:
              msg: "{{ system_uptime }}"
