---  
- name: Debug Example Uptime  
  hosts: main
  become: true
   
  tasks:  
   - name: Find Uptime  
     shell: /usr/bin/uptime  
     register: result  
   
   - name: Print debug message  
     debug:  
      var: result.stdout  
