---
- name: Ansible debug module in action
  hosts: main
  gather_facts: false
  vars:
     greetings: DevopsforAll
     site: devopsforall.in
  tasks:
    - name: Print the value of a variable
      debug:
       msg: "{{ lookup("env", "greetings") }}, Welcome to {{ lookup("env", "site") }}."
