---
- name: demo playbook to check ignore erros
  hosts: main
  gather_facts: false
  become: true
  serial: 1
  strategy: free
  vars:
     service: nginx
  tasks:
    - name: print the service name
      debug:
        var: service
    - name: check if nginx present
      shell: systemctl status nginx |grep running
      register: check
      ignore_errors: true
    - name: install pkg if not exists
      package:
         name: "{{ item }}"
         state: present
      loop:
         - "{{ service }}"
