---
- name: demo playbook for when condition with loops
  hosts: main
  gather_facts: true
  become: true
  serial: 1
  strategy: free
  
  vars:
    username:
     - ubuntu
     - centos

  tasks:
   - name: create user on server
     user:
       name: "{{ item }}"
       state: present
       password: "{{  item | password_hash('sha512') }}"
     loop: "{{ username }}"
     when: (item == "ubuntu" and ansible_distribution | lower == "ubuntu") or (item == "centos" and ansible_distribution | lower == "centos")
