---
- hosts: localhost
  gather_facts: false
  vars:
    debugging: true
  tasks:
    - block:
        - name: First Task
          debug:
            msg: First Task

        - name: Set debugging To False
          set_fact:
            debugging: false

        - name: Second Task
          debug:
            msg: Second Task
      when: debugging|bool
