# aws ec2 ansible dynamic inventory plugin
# https://faun.pub/learning-the-ansible-aws-ec2-dynamic-inventory-plugin-59dd6a929c7f
plugin: aws_ec2
aws_profile: default
regions: 
 - us-west-2
strict: True
filters:
  instance-state-name : running
keyed_groups:
  - key: tags.Name
  - prefix: instance_type
    key: instance_type
  - key: placement.region
    prefix: aws_region
hostnames:
  - private-ip-address
