---
- name: Getting facts from all the servers
  hosts: main
  gather_facts: false

  pre_tasks:
  - name: getting filtered facts
    setup:
      filter:
        - 'ansible-*'

  tasks:
  - name: displaying facts via ansible facts
    debug:
      var: ansible_facts

  - name: display facts via hostvars
    debug:
      var: hostvars
