---
- name: Ansible Variable Example Playbook
  hosts: main
  tasks:

    # Print the Dictionary
    - debug:
        msg: "{{ansible_mounts}}"

    # Parsing through Variable Dictionary
    - debug:
        msg: "Mount Point {{item.mount}} is at {{item.block_used/item.block_total*100}} percent "
      loop: "{{ansible_mounts}}"

    # Execute Host based task using variable
    - name: Execute the command to get hostname
      become: yes
      become_user: root 
      shell: "uname -a"
      register: result

    - debug:
        var: result.stdout
