---
- name: filesystem details
  hosts: "{{ serv }}"
  remote_user: "{{ user }}"
  become: true
  become_method: sudo
  serial: 1
  become_user: root 
  gather_facts: false
  ignore_unreachable: true
  tasks:
  - name: Get filesystem Details
    shell: df -h
    register: space
  - name:  "filesytem details on {{ inventory_hostname }} is"
    debug:
     msg: "{{ space.stdout }}"
