---
- name: Checking if server is pingable
  hosts: "{{ serv }}"
  remote_user: "{{ user }}"
  become: true
  become_method: sudo
  become_user: root 
  gather_facts: false
  ignore_unreachable: true
  tasks:
      - name: Test Ping Connection
        ping:
