---

- hosts: managed1 (Name of your target node)

gather_facts: no

become: true

tasks:

- name: Replace module demo

ansible.builtin.replace:

path: /etc/ssh/sshd_config

regexp: 'yes'

after: 'PubkeyAuthentication'

replace: 'no'
