- name: Package Installation
  hosts: main
  gather_facts: false
  become: true

  tasks:

    - name: Updating cache ( sudo apt update )
      apt:
        update_cache: true
      tags: cache_update

    - name: Remove packages - no dependency
      apt:
        autoremove: yes
      tags: remove
