- hosts: main
  vars_prompt:
     - name: dvd_dir
       private: no
       prompt: "enter dvd mount point"
  tasks:
  - name : print the var details you just entered
    shell: "echo {{ dvd_dir }}"
    register: output
    changed_when: 

  - debug:
      var: output
